name: CIFuzz
on:
  schedule:
    - cron: "*/107 * * * *"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/master' || github.sha }}
  cancel-in-progress: true

jobs:
  fuzzer:
    name: Fuzzer
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fuzzer: [duckfuzz, sqlsmith, duckfuzz_functions]
        data: [alltypes, tpch, emptyalltypes]
    env:
      BUILD_SQLSMITH: 1
      BUILD_ICU: 1
      BUILD_JSON: 1
      BUILD_TPCH: 1
      BUILD_TPCDS: 1
      BUILD_PARQUET: 1
      BUILD_JEMALLOC: 1
      CRASH_ON_ASSERT: 1
      GEN: ninja
      FUZZEROFDUCKSKEY: ${{ secrets.FUZZEROFDUCKSKEY }}

    steps:
      - name: Dependencies
        shell: bash
        run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build ccache

      - name: Setup Ccache
        uses: hendrikmuhs/ccache-action@main

      - uses: actions/checkout@v3
        with:
          repository: duckdb/duckdb
          fetch-depth: 0

      - uses: actions/checkout@v3
        with:
          path: fuzzer

      - name: Build
        shell: bash
        run: |
            make debug

      - name: Fuzz
        shell: bash
        run: |
            python3 fuzzer/run_fuzzer.py  --${{ matrix.fuzzer }} --${{ matrix.data }} --shell=build/debug/duckdb
