name: CIFuzz
on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "*/107 * * * *"

jobs:
  build-duckdb:
    name: Build DuckDB
    uses: ./.github/workflows/reusable_build.yml
    with:
      git_url: ${{ github.actor }}
      git_tag: ${{ github.ref_name }}
      timeout-minutes: 1
      # timeout-minutes: 120

  fuzzer:
    name: Fuzzer
    needs:
    - build-duckdb
    strategy:
      fail-fast: false
      matrix:
        fuzzer: [duckfuzz, sqlsmith, duckfuzz_functions]
        data: [alltypes, tpch, emptyalltypes]
    uses: ./.github/workflows/reusable_fuzzer.yml
    with:
      fuzzer: ${{ matrix.fuzzer }}
      data: ${{ matrix.data }}
      timeout-minutes: 1
      # timeout-minutes: 120
      dry: dry
      max_queries: 1
      # max_queries: 1000
    secrets:
      FUZZEROFDUCKSKEY: ${{ secrets.FUZZEROFDUCKSKEY }}
      DUCKDB_HASH: ${{ needs.build-duckdb.outputs.duckdb-hash }}

  check-issues:
    name: Check existing issues
    needs:
    - build-duckdb
    runs-on: ubuntu-latest
    env:
      FUZZEROFDUCKSKEY: ${{ secrets.FUZZEROFDUCKSKEY }}
      DUCKDB_HASH: ${{ needs.build-duckdb.outputs.duckdb-hash }}

    steps:
      - uses: actions/checkout@v4
        with:
          repository: duckdb/duckdb_sqlsmith
          path: duckdb_sqlsmith
          sparse-checkout: |
            scripts

      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: duckdb

      - name: Fuzz
        shell: bash
        run: |
            chmod +x duckdb
            cd duckdb_sqlsmith
            python3 scripts/run_fuzzer.py --duckfuzz --alltypes --shell=../duckdb
